
INSERT INTO vrehwe9wmkudwfl8.workouts (muscleGroup, workout, videoLink)
VALUES ("Chest", "Barbell Bench Press", "ysUTNll8JQ8"),
("Chest", "Dumbbell Bench Press", "VmB1G1K7v94"),
("Chest", "Barbell Incline Bench", "SrqOu55lrYU"),
("Chest", "Dumbbell Incline Bench", "0G2_XV7slIg"),
("Chest", "Chest Flyes", "eozdVDA78K0"),
("Legs", "Barbell Squat", "1oed-UmAxFs"),
("Legs", "Dumbbell Lunges", "D7KaRcUTQeE"),
("Legs", "Seated Leg Press", "EjCWVkP0cYM"),
("Legs", "Leg Extensions", "9nmAtebIwy8"),
("Legs", "Calf Raises", "IoZiWPV6htA"),
("Biceps", "Standing Curls", "yTWO2th-RIY"),
("Biceps", "Hammer Curls", "7jqi2qWAUJk"),
("Biceps", "Precher Curls", "fIWP-FRFNU0"),
("Biceps", "Reverse Curls", "nRgxYX2Ve9w"),
("Biceps", "Overhead Cable Curls", "d4YaCgGG-so"),
("Triceps", "Rope Tricep Pushdown", "REWv05om0ho"),
("Triceps", "Tricep Dips", "35PXVWP1XVs"),
("Triceps", "Overhead Tricep Extension", "-Vyt2QdsR7E"),
("Triceps", "Lying Tricep Extension", "IkL7ABXO7HQ"),
("Triceps", "Diamond Press-Up", "J0DnG1_S92I"),
("Shoulders", "Dumbbell Shoulder Press", "qEwKCR5JCog"),
("Shoulders", "Arnold Press", "X60-yTMOJfw"),
("Shoulders", "Front Lateral Raises", "sH_5J6lcvJk"),
("Shoulders", "Side Lateral Raises", "b_LEX4n9lOs"),
("Shoulders", "Upright Row", "amCU-ziHITM"),
("Back", "Pull Ups", "eGo4IYlbE5g"),
("Back", "Bent-Over Row", "6TSP1TRMUzs"),
("Back", "Seated Cable Row", "sP_4vybjVJs"),
("Back", "Lat Pulldown", "CAwf7n6Luuc"),
("Back", "Kettlebell Swings", "bMQHAmCXJAI"),
("Cardio", "Elliptical", "E15Q3Z9J-Zg"),
("Cardio", "Treadmill", "xJlztO0JeIo"),
("Cardio", "Bicycle", "XVlXHG-P9YY"),
("Cardio", "Rowing Machine", "w2hGNM4l5so"),
("Cardio", "Stairmaster", "QqLXUA4ZnL4"),
("Abs", "Sit Ups", "1fbU_MkV7NE"),
("Abs", "Ab Wheel", "Ulduc3QuBXg"),
("Abs", "Leg Lifts", "l-mPHKQFMkk"),
("Abs", "Planks", "ASdvN_XEl_c"),
("Abs", "Russian Twists", "NeAtimSCxsY");